### ISSUE TITLE
Error parsing certificate request

### ISSUE THREAD

**Issue by tiagogeraldi** [unixcharles/acme-client#101]
Any thoughts about this?
```
*** Acme::Client::Error::Malformed Exception: Error parsing certificate request. Extensions in the CSR marked critical can cause this error: https://github.com/letsencrypt/boulder/issues/565
```
It occurs when I call `@client.new_certificate(csr)`.
My certificate has an extension but it's not marked critical.
I set `endpoint = 'https://acme-staging.api.letsencrypt.org/'`
Is it a problem in my key? Or is it a bug generating the certificate request?

Thank you

**Comment by unixcharles** [comment]
That would be a behaviour of [boulder](https://github.com/letsencrypt/boulder). The client is just raising the error that came from the server.
