### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by weppos** [unixcharles/acme-client#105]
I've just noticed master contains some changes not available in the latest version on RubyGems (0.4.1).

Ironically, I needed a way to fetch an Authorization and I started working on a patch, when I realized that the method was there in master (but not in the gem I had installed) as it was merged in #99.

Any chance to get a new version released?

**Comment by unixcharles** [comment]
Just released 0.5.0 now

**Comment by weppos** [comment]
Thanks! ❤️
