### ISSUE TITLE
Unspecified dependency on json gem

### ISSUE THREAD

**Issue by boxcycle** [unixcharles/acme-client#107]
FYI, I got the following error (same in latest 0.5 version): "/acme-client-0.4.1/lib/acme/client/crypto.rb:11:in `dup': [bug] frozen object (JSON::Ext::Generator::State) allocated                                                            (TypeError)" 

It turned out that I needed to upgrade the json gem from version 1.8.3 I had installed to get things working.  The current version is 2.0.2.

**Comment by unixcharles** [comment]
I'm not sure which gem you are referring too.

We test against JSON from the standard library but any compatible adapter should work out of the box.
