### ISSUE TITLE
REQUEST: Support for multiple domains

### ISSUE THREAD

**Issue by vtt** [unixcharles/acme-client#119]
Will multiple domains be supported? Currently, it only authorizes example.com and www.example.com

**Comment by unixcharles** [comment]
Yes, you can authorize multiple domains. Once you have completed all the challenge just generate the CSR with multiple `subjectAltNames`.

Is that your question?

**Comment by vtt** [comment]
I tried doing that but it doesn't work.  I followed the examples as below:

...
authorization = client.authorize(domain: 'example.org')
...
csr = Acme::Client::CertificateRequest.new(names: %w[example.org one.example.org two.example.org three.example.org])
certificate = client.new_certificate(csr)

and I get the below exception error:
Acme::Client::Error::Unauthorized: Error creating new cert :: Authorizations for these names not found or expired: one.example.org, two.example.org, three.example.org

Do I need to add all the domains in the authorization stub?

**Comment by unixcharles** [comment]
CSR generation is not part of acme, its just normal PKI stuff.

You'll need to authorize each domains, and complete the challenge for each of them, and all of that on the same account.

```ruby
authorization1 = client.authorize(domain: 'example.org')
authorization2 = client.authorize(domain: 'one.example.org')
authorization3 = client.authorize(domain: 'two.example.org')

# ...
csr = Acme::Client::CertificateRequest.new(names: %w[example.org one.example.org two.example.org three.example.org])
certificate = client.new_certificate(csr)
```

**Comment by vtt** [comment]
I understand now.  Thank you for your explanations.

**Comment by unixcharles** [comment]
No problem.
