### ISSUE TITLE
Renewing certificate

### ISSUE THREAD

**Issue by herberzt** [unixcharles/acme-client#122]
Is there any documentation explaining how to renew a certificate that is about to expire?

**Comment by unixcharles** [comment]
No. There is no concept of renewal in the acme protocol. You just order a new certificate like if it was the first time.

**Comment by jhass** [comment]
However note that you could (not saying it's recommended) use the same private key or even CSR again though.

**Comment by herberzt** [comment]
@jhass we don't want to have to generate a new SSL challenge token everytime we get a new cert.

**Comment by unixcharles** [comment]
> @jhass we don't want to have to generate a new SSL challenge token everytime we get a new cert.

You'll need to complete the challenge every time.
