### ISSUE TITLE
Challenge authorization

### ISSUE THREAD

**Issue by jimmybaker** [unixcharles/acme-client#124]
According to the readme, I should be checking `challenge.authorization.verify_status` or `authorization.verify_status` of which both are undefined. Has the library changed so that I can just refer to `challenge.verify_status` now?

**Comment by unixcharles** [comment]
Both should work. The challenge classes delegate to their authorization part, so technically, its the same thing.

I'm really not sure how you end up with `nil` here. Do you have a bit more information on what's happening / how are you using the library? What version are you using?
