### ISSUE TITLE
ACME v2

### ISSUE THREAD

**Issue by bdewater** [unixcharles/acme-client#126]
https://letsencrypt.org/2017/06/14/acme-v2-api.html coming in January 2018 with no plans for now to sunset v1.

From HN: https://github.com/letsencrypt/pebble should aid in development and testing

**Comment by cimnine** [comment]
I would also like to know what the plans of @unixcharles are for supporting acme-v2.

The latest draft is published at https://tools.ietf.org/html/draft-ietf-acme-acme, while it's development happens at https://github.com/ietf-wg-acme/acme .

**Comment by unixcharles** [comment]
> I would also like to know what the plans of @unixcharles are for supporting acme-v2.

Sorry if it seem like I just ignored the issue. @bdewater and I work together, so we had IRL conversation about it. This is not very transparent, I'll try to avoid doing that in the future.

I'm aware of the development in the spec/boulder.

The tl;dr is yes, I intend to have the client implement the spec v2.

Its a bit of a time consuming effort but I'll try to have it ready for the launch in January. Last time I've looked into the new spec there was no server implementation, and that makes it difficult develop / test, so this is the reason why v2 was on hold.

**Comment by calavera** [comment]
You're probably already aware, but I just wanted to leave you a note about the new public staging V2 endpoint:

https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605

**Comment by elcool0r** [comment]
I'm cheering for you. Patiently waiting for the new acme gem to get started with the migration of my tools :)

**Comment by maran** [comment]
@unixcharles and @bdewater do you still have time to build ACME v2 support before the production endpoint goes live by the end of February? If so I would love to sponsor the development as you guys made my life a lot easier the past year since I've started using the library.

**Comment by unixcharles** [comment]
Hey @maran, I just didn't have time to give it a shot yet but I will put some time into it to be ready for the launch.

From my understand there should be minimal changes compared to acme draft 07. Pretty hype about getting those sweet wildcard certificates.

**Comment by elcool0r** [comment]
hey there, 
I really don't wanna annoy you but could you tell us if you still plan to be ready this month? 

thanks!

**Comment by unixcharles** [comment]
Hey @elcool0r,

These a lot more change to the API than originally expected. All the endpoint have changed and the communication layer changed too, so this is basically a re-write at this point, but I'm doing some progress. I'm still hoping to be ready for launch.

I have managed to upgrade the faraday middleware that handle basic communication (jws/nounce/etc).

I've already implemented endpoint for account management (create/TOS/update/deactivate) and basic order creation.

I still need to implement authorization / challenge completion, certificate ordering and re-key.

You can check out the [acme-v2](https://github.com/unixcharles/acme-client/compare/acme-v2?expand=1) branch to get an idea of where I'm at.

**Comment by elcool0r** [comment]
Thanks for the update!

**Comment by will-in-wi** [comment]
Noting here that wildcard/ACMEv2 is live! https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by unixcharles** [comment]
Just a quick update. https://github.com/unixcharles/acme-client/compare/acme-v2 is progressing. I have most of the spec implemented. I have a few more call to implement, downloading certificate and revocation and I also need to write some more tests. It should be up for review soon and expect a release soon after.

**Comment by unixcharles** [comment]
I have a PR up for review https://github.com/unixcharles/acme-client/pull/134

**Comment by unixcharles** [comment]
v2 is out.

Bumped the version to v2 to match the spec.

Also released a v1 for the legacy acme v1 protocol and moved its development into the [acme-v1](https://github.com/unixcharles/acme-client/tree/acme-v1) branch.
