### ISSUE TITLE
Issue upgrading from v1 to v2 on Heroku Platform API

### ISSUE THREAD

**Issue by richardonrails** [unixcharles/acme-client#147]
I'm trying to upgrade from v1 to v2 and am having some trouble integrating it with Heroku's platform API now.

Is v2's `certificate` now equivalent to v1's `certificate.to_pem` or `certificate.fullchain_to_pem`? If it's the former, is there a way to access the latter now?

I had this working in v1:

```rb
certificate = client.new_certificate(csr)

endpoint.update(heroku_app, certificates[0]['name'], {
  certificate_chain: certificate.fullchain_to_pem,
  private_key: certificate.request.private_key.to_pem
})
```

I have this in v2 (doesn't work):

```rb
certificate = order.certificate

endpoint.update(heroku_app, heroku_certificates[0]['name'], {
  certificate_chain: certificate,
  private_key: csr.private_key
})
```

**Comment by unixcharles** [comment]
The API now return the full chain by default. This is the reason I deprecated the abstraction in between.

The certificate is a string, you should be able to inspect it.

**Comment by unixcharles** [comment]
Maybe https://stackoverflow.com/questions/25771090/heroku-no-valid-non-passphrase-protected-keys-given-error

**Comment by richardonrails** [comment]
I edited my previous comment soon after posting. In my command line test (`sudo heroku certs:update cert.pem cert.key`) it's actually working fine (first time around, I missed the `-----END RSA PRIVATE KEY-----` when I copied the key over to a file) -- so I didn't really have a passphrase or any cli error. However issue remained with the code above when using the Heroku Platform API directly. 

However I just figured it out...

It turns out I needed to pass `csr.private_key.pem` instead of just `csr.private_key` in the new code block above. While the latter printed the private key correct in a debug `puts`, Heroku's platform client `endpoint.update` did not like receiving a `<OpenSSL::PKey::RSA:0x00007fcae4fbfc28>` instead of a string.

You may consider documenting usage of `csr.private_key.to_pem` to help avoid confusion.

Thanks for your hard work on this project!
