### ISSUE TITLE
Error: unknown keyword: endpoint

### ISSUE THREAD

**Issue by TheR2** [unixcharles/acme-client#159]
unknown keyword: endpoint

`/var/lib/gems/2.6.0/gems/acme-client-2.0.2/lib/acme/client.rb:32:in 'initialize'
/data/letsencrypt/authorize_domain.rb:17:in 'new'
/data/letsencrypt/authorize_domain.rb:17:in '<top (required)>'
/data/renew.rb:18:in 'require_relative'
/data/renew.rb:18:in '<main>'`

This is possibly ruby 2.6 related error, since I only recently updated to ruby 2.6.

Reverted gem to acme-client v.1.0.0 and it works.

by
TheR

**Comment by unixcharles** [comment]
The gem follow normal semantic versioning, you should expect API changes between major versions. 

`acme-client` v1 implement ACME version 1 and acme-client 2 implement ACMEv2.

The protocol is not the same between the two versions and the client changes reflect that.

The readme explain how to initialize a client object.
