### ISSUE TITLE
Is the example code for waiting for `order.finalize` correct?

### ISSUE THREAD

**Issue by jalada** [unixcharles/acme-client#161]
The README contains this code snippet:

```ruby
order.finalize(csr: csr)
sleep(1) while order.status == 'processing'
```

However looking at [the definition for `Acme::Client::Resources::Order`](https://github.com/unixcharles/acme-client/blob/master/lib/acme/client/resources/order.rb), `status` is just an `attr_reader`. I can't see what would change it in between the comparisons.

Apologies if I'm missing something! I thought it best to check.

**Comment by unixcharles** [comment]
You are right, you should call reload to refresh the status. I will update the readme.

**Comment by jalada** [comment]
Thanks!
