### ISSUE TITLE
challenge.request_validation returning invalid in DNS01 challenge type

### ISSUE THREAD

**Issue by advir29** [unixcharles/acme-client#172]
challenge.request_validation is returning status as **invalid** in DNS01 challenge type.
I have checked with txt DNS records. Challenge text, etc. are properly applied. I have also ensured to wait before requesting validation of challenge so that those records propagate properly.
It was working a month or so ago.
I am new to this. 
Request you to suggest any other probable cause I need to address to resolve this issue?

**Comment by cpu** [comment]
:wave: Hi @advir29,

Are you using `acme-client` with Let's Encrypt? If so we would be happy to help you debug the issue over at the Let's Encrypt community forum: https://community.letsencrypt.org You can start by opening a new topic in the "Help" section and completing as many of the template questions as you can. Likely this is a problem with your deployment and not a bug with `acme-client` itself.

**Comment by advir29** [comment]
Hello @cpu ,
As you asked I have created a new topic.
https://community.letsencrypt.org/t/challenge-request-validation-returning-status-as-invalid-in-dns01-challenge-type/107181?u=advir29
Thanks!

**Comment by advir29** [comment]
This issue occurred due to the unreliability of my TLD. A workaround suggested on community forum fixed the issue.
If interested the link to the thread is
https://community.letsencrypt.org/t/challenge-request-validation-returning-status-as-invalid-in-dns01-challenge-type/107181
Thanks !
