### ISSUE TITLE
Attribute.new missing 'value='

### ISSUE THREAD

**Issue by paradisaeidae** [unixcharles/acme-client#184]
Hi  dgholz and Daniel Holz,
Thanks for this gem!
I've been using it a while.
It is instructive!
Recently I upgraded a VM to Ubuntu 20.
I've found a bit of an issue with:
 newAtt = OpenSSL::X509::Attribute.new( 'extReq', setSeq)
For some reason the method: value= is no longer available here.

I've upgraded openssl to 1.1.1g.
Recompiled Ruby 2.7.1.
Recompiled the Ruby Openssl gems to pristine.
Regenerated acme-client to pristine.
Checked my ld-configs.
Rebooted a number of times.
Attempted with different versions of acme gems.
With different versions of Ruby.
The call lands at:
https://ruby-doc.org/stdlib-2.7.1/libdoc/openssl/rdoc/OpenSSL/X509/Attribute.html

This arrives at some c code as part of ruby.
Today this is not part of my debugging techniques.
I've cloned your repo to get to a testing scenario.
What is the process for testing?

I am a bit befiddled/fuddled.
Now I look in mkmf.log for ruby 1.7.1 ext/openssl
I see many errors.
I check cc version, see cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Ubi 19.10 cc is cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Attempt to compile with gcc-8 brings the same issue.

Adjacent to this I'm finding the inbuilt ruby did-you-mean is causing a hard stop for ruby.
original_message or to_s being dangerous, return out to bypass crash.

So far my exploration is suspecting the change to glibc being relevant.
UB-19.10 uses ldd (Ubuntu GLIBC 2.30-0ubuntu2.1) 2.30
UB-20              ldd (Ubuntu GLIBC 2.31-0ubuntu9) 2.31

**Comment by unixcharles** [comment]
I'm not sure what is the problem but the standard library for OpenSSL has not really changed in 2.7. We are running the CI on ruby 2.7 and this code path is working fine. Something must be wrong with your setup.

That said, you don't have to use the `Acme::Client::CertificateRequest` class. It's an helper method but you could just create a CSR yourself if that easier for you.

**Comment by paradisaeidae** [comment]
Thanks, yes, agreed. It is moi!
