### ISSUE TITLE
Support for fetching alternative certificates

### ISSUE THREAD

**Issue by gschorkopf** [unixcharles/acme-client#186]
### Problem

ACME client should support the ability to look up alternative certificates in order to continue using the IdenTrust chain during the yearlong gap (Sept 29 2020 to 2021) where Let's Encrypt will continue to cross-sign but are now using their own chain by default.

### Potential Solutions

1. Upgrading the [certificate](https://github.com/unixcharles/acme-client/blob/v2.0.5/lib/acme/client.rb#L130-L133) method to loop and download certificates until one matches the certificate authority expected. This is roughly what certbot is doing (see below)
2. Add a new method that will return all (including alternatives) certificates

### Notes

[Context on Transitioning to ISRG's root](https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html)

There are additional details [here](https://community.letsencrypt.org/t/transition-to-isrgs-root-delayed-until-sep-29/125516/2) for Let's Encrypt's decision to:

> to start serving certificates with the “alternate” link relation to allow ACME clients to programmatically select a chain they prefer

There is a python implementation of this feature for [certbot here](https://github.com/certbot/certbot/pull/8080). Perhaps we could take a queue from the [tests they've written](https://github.com/certbot/certbot/pull/8080/files#diff-1b881d1b819f210cc99be0fc88e8fbe8R845).

In a world with many alternatives, it seems like you need to download them in order to understand how they operate. The links header only returns a URL for download with no additional information. The link header (in ruby) looks roughly like this:

```ruby
"link"=>
 {"index"=>"https://acme-v02.api.letsencrypt.org/directory",
  "alternate"=>"https://acme-v02.api.letsencrypt.org/acme/cert/longcert_id/1"}
```

I've done a bit of research. Today, the alternates (though there is only one) is the certificate that uses Let's Encrypt's chain. I imagine on Sept 29th the original and alternate certificates will swap (though have not confirmed this).

**Comment by gschorkopf** [comment]
By the way, we are planning to do this work and contribute to this gem, hoping to use the work ahead of the Sept 29 deadline! Just wanted to make the issue publicly visible for y'all.

**Comment by elct9620** [comment]
Oops, I miss this issue. I will subscribe to this issue for the update.

**Comment by sawanoboly** [comment]
@unixcharles Hi, could you please your opinion on this Issue?

**Comment by unixcharles** [comment]
You can use `force_chain` in `2.0.7`.

Thanks everyone
