### ISSUE TITLE
EAB support

### ISSUE THREAD

**Issue by sebyx07** [unixcharles/acme-client#198]
I have some issues integrating it with zerossl, because acme-client doesn't support `eab-kid` and `hmac-key`

https://github.com/zerossl/certbot-zerossl/blob/ad5dae70b3b1808807f1a77c0ca9293bed2caabf/certbot-zerossl.sh

And I get this error:
`Acme::Client::Error::ExternalAccountRequired: The request must include a value for the "externalAccountBinding" field`

**Comment by unixcharles** [comment]
What is eab-kid? Is it part of the spec?

I would be open to add support for zerossl

**Comment by kwatson** [comment]
Just jumping in on this: Yes, EAB (External Account Binding) is part of the ACME spec: https://tools.ietf.org/html/rfc8555#section-7.3.4

`eab-kid` is the identifier provided by the CA that needs to be included in the EAB payload.

Would also love to have ZeroSSL support! 😄

**Comment by cotin18** [comment]
YES PLEASE!! 
:smile:

**Comment by unixcharles** [comment]
now supported
