### ISSUE TITLE
DIRECTORY_DEFAULT error

### ISSUE THREAD

**Issue by technion** [unixcharles/acme-client#2]
Hi,

I've found in my environment, when run as:

    bundle exec rake spec

Nearly every test fails. I've tracked it to an issue I can replicate in irb:

    2.2.0 :001 > private_key = OpenSSL::PKey::RSA.new(2048)
     => #<OpenSSL::PKey::RSA:0x007faf5aed1fa0>
    2.2.0 :002 > endpoint = 'https://www.letsencrypt-demo.org/acme'
     => "https://www.letsencrypt-demo.org/acme"
    2.2.0 :003 > client = Acme::Client.new(private_key: private_key, endpoint: endpoint)
    NameError: uninitialized constant Acme::Client::DIRECTORY_DEFAULT

I don't know where this constant is supposed to come from, but it only appears once in the codebase, the place it's used:

    $ grep -r DIRECTORY_DEFAULT *
    lib/acme/client.rb:      DIRECTORY_DEFAULT

I'd be happy to try and create a default and submit a PR - but you have a lot of tests and it looks like you obviously had this defined in your environment. Is there a file that didn't get committed properly?

I've also noted a failure if I try to assign a directory uri. I'm unsure if it's related:

    client = Acme::Client.new(private_key: private_key, endpoint: endpoint,     directory_uri: "https://www.letsencrypt-demo.org/directory")
    NoMethodError: undefined method `fetch' for #<String:0x007f7520bbe2b0>
        from lib/acme/client.rb:56:in `load_directory!'

**Comment by technion** [comment]
Just an update on this. I would send a PR but I still can't get a single test to pass. I have however, got fixes for the above two issues.

The obvious fix for the immediate issue would be to declare this somewhere:

DIRECTORY_DEFAULT = { "new-authz" => "https://acme-staging.api.letsencrypt.org/acme/new-authz", "new-cert" => "https://acme-staging.api.letsencrypt.org/acme/new-cert","new-reg" => "https://acme-staging.api.letsencrypt.org/acme/new-reg","revoke-cert" => "https://acme-staging.api.letsencrypt.org/acme/revoke-cert"}

This resolves it for use against the demo server, but would require changing at golive.

The "fetch" issue I've pasted above is definitely a thing. I've posted a quick walkthrough of how the current code plays out in the load_directory function:

2.2.0 :008 > response = client.connection.get('https://www.letsencrypt-demo.org/directory')
 => #<Faraday::Response:0x007f73769437e8 2.2.0 :009 > ...

2.2.0 :009 >body = response.body
 => "{\"new-authz\":\...

2.2.0 :010 > newreg = body.fetch('new-reg')
NoMethodError: undefined method `fetch' for #<String:0x007f7376b48ef8>
        from (irb):10
        from bin/console:14:in `<main>'

I think we can address two issues in one patch, by defining the "default" as a directory path.

I've written a gist here: https://gist.github.com/technion/b4eac8ba7b08a677a21d with a patch that resolves this for me. With this gist in place, I can successfully walk through your README using the https://www.letsencrypt-demo.org/ endpoint, both by defining a directory_uri and by leaving it out.

As I said, I would have made this a PR, but I can't get any tests to pass. I'm unsure if I'm missing something else in that regard.

Any assistance appreciated.

**Comment by technion** [comment]
Further update: Even though it returns json, the reference server is setting:

Content-Type: text/plain; charset=utf-8
In the directory lookup. Looking at the middleware I'm expecting this is the issue.

**Comment by unixcharles** [comment]
Hi @technion, sorry on they delays. I fixed it [here](https://github.com/unixcharles/acme-client/commit/935de2a2112dc958d74b012bd9943ef0586edf17).

Can you checkout the latest master and let me know if everything is working well on your end when running the tests?
