### ISSUE TITLE
 Order's status ("invalid") is not acceptable for finalization (Acme::Client::Error)

### ISSUE THREAD

**Issue by imsny28** [unixcharles/acme-client#216]
Kindly let me know solution for this.

**Comment by official-imsny** [comment]
### ERROR!
	10: from /var/lib/gems/2.7.0/gems/acme-client-2.0.11/lib/acme/client/resources/order.rb:23:in `finalize'
	 9: from /var/lib/gems/2.7.0/gems/acme-client-2.0.11/lib/acme/client.rb:149:in `finalize'
	 8: from /var/lib/gems/2.7.0/gems/acme-client-2.0.11/lib/acme/client.rb:299:in `post'
	 7: from /var/lib/gems/2.7.0/gems/faraday-2.5.2/lib/faraday/connection.rb:281:in `post'
	 6: from /var/lib/gems/2.7.0/gems/faraday-2.5.2/lib/faraday/connection.rb:445:in `run_request'
	 5: from /var/lib/gems/2.7.0/gems/faraday-2.5.2/lib/faraday/rack_builder.rb:153:in `build_response'
	 4: from /var/lib/gems/2.7.0/gems/acme-client-2.0.11/lib/acme/client/faraday_middleware.rb:23:in `call'
	 3: from /var/lib/gems/2.7.0/gems/faraday-2.5.2/lib/faraday/response.rb:42:in `on_complete'
	 2: from /var/lib/gems/2.7.0/gems/acme-client-2.0.11/lib/acme/client/faraday_middleware.rb:23:in `block in call'
	 1: from /var/lib/gems/2.7.0/gems/acme-client-2.0.11/lib/acme/client/faraday_middleware.rb:38:in `on_complete'
/var/lib/gems/2.7.0/gems/acme-client-2.0.11/lib/acme/client/faraday_middleware.rb:54:in `raise_on_error!': Order's status ("invalid") is not acceptable for finalization (Acme::Client::Error)

**Comment by unixcharles** [comment]
The server is returning `{ "type": "urn:ietf:params:acme:error:malformed", "detail": "Order's status ("invalid") is not acceptable for finalization", "status": 400 }`

I'm assuming the challenge has not been completed or failed. Anyhow its an error from the server.
