### ISSUE TITLE
Acme::Client::Error::CertificateNotReady: No certificate_url to collect the order

### ISSUE THREAD

**Issue by willzoltan** [unixcharles/acme-client#226]
We're seeing the error `Acme::Client::Error::CertificateNotReady: No certificate_url to collect the order` being raised on all of our cert requests.

Here is where the error is thrown (on the `certificate` method of the order):
```ruby
order = lets_encrypt_client.new_order(identifiers: domains_for_certificate)
order.certificate
```

Here is the traceback:
```
Acme::Client::Error::CertificateNotReady: No certificate_url to collect the order
  File "/usr/local/bundle/gems/acme-client-2.0.8/lib/acme/client/resources/order.rb", line 31, in certificate
```

Our acme client version is 2.0.8.

We've been happily processing thousands of SSL certs and now we're seeing this error being raised on all SSL certs. Any ideas how to address it?

**Comment by tdegrunt** [comment]
Same here, this may be why: https://letsencrypt.status.io/

**Comment by tdegrunt** [comment]
Seems fixed!
