### ISSUE TITLE
CSR generator

### ISSUE THREAD

**Issue by jhass** [unixcharles/acme-client#24]
A very common task when using this library will be generating a CSR. Ruby's OpenSSL API is rather inconvenient, especially when it comes down to including a `subjectAltName` extension.

Should we provide a convenience class to ease CSR generation? What would the interface look like? First thoughts would be to keep it as simple as `client.new_certificate(%w(example.org www.example.org), private_key)`, `client.new_certificate(Acme.generate_csr(%w(example.org www.example.org), private_key)` or `client.new_certificate(Acme::Csr.new(%w(example.org www.example.org), private_key))`. The first hostname would be picked for the `CN`.

**Comment by unixcharles** [comment]
I agree.

If we can save anyone from having figuring out what's an "OpenSSL::X509::ExtensionFactory" or a "OpenSSL::ASN1::UTF8STRING", that would be for the best.

I would also like to provide the most commonly used optional fields to cover most use cases.

Maybe something in the line of:

```ruby
Acme::CertificateSigningRequest.new(
  common_name: 'example.org',
  key_pair: key_pair,
  subject_alt_names: ['www.example.org'],
  subject: { organization_name: 'example', email: 'hostmaster@example.com', country_name: 'CA', state_or_province_name: 'Quebec', locality_name: 'Montreal'}
)
```

Also, ensure the client work with PEM formatted string or any object that respond to `to_pem`. This way users are free do use `OpenSSL::X509::Request` directly or whatever else that fit their needs.

**Comment by dkam** [comment]
Is it worth abstracting this a bit further, perhaps into the ACME::Certificate?  It could be in two states - not signed ( write access to the CSR ) or signed ( read access to the certificate attributes )?  

The steps would be, create a certificate, set the appropriate attributes ( subjectAltName ), then request the certificate be signed.  Attempting to write the certificate without it being signed would raise an exception. Attempting to set values after it is signed would raise an exception.

**Comment by jhass** [comment]
I'm not sure that makes handling easier. Requesting your certificate is a quite essential step you should have full control over, doing it implicitly somewhere at all seems wrong. I also can imagine code to become more brittle by allowing to pass around an unsigned certificate, keeping them separate means when you got an `Acme::Certificate` you know you got a valid cert.
