### ISSUE TITLE
fullchain_to_pem puts certificates in wrong order? 

### ISSUE THREAD

**Issue by dkam** [unixcharles/acme-client#28]
I believe the certificate needs to be listed first within the file, followed by the chain.  Currently the certificate is at the end of the file.  Creating a full chain certificate currently produces the follow error with Nginx: 

```
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/booko2/booko.2015.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
```
Using the openssl client we're given details of the root, not the certificate. 

Swapping the order of the certificates creates an full chain certificate that Nginx can correctly load.

If that's right, then lib/acme/certificate.rb should be changed from 

```
  def fullchain_to_pem
    [*x509_chain, x509].map(&:to_pem).join
  end
```

to 

```
  def fullchain_to_pem
    [x509, *x509_chain].map(&:to_pem).join
  end
```

**Comment by jhass** [comment]
Yeah, I [got it wrong](http://nginx.org/en/docs/http/configuring_https_servers.html#chains), this stuff is confusing!

**Comment by unixcharles** [comment]
thanks for reporting

**Comment by dkam** [comment]
Thanks for writing / fixing it. Nginx doesn't give you a very helpful error - there's nothing wrong with the key, it's just that it's looking at the wrong certificate.
