### ISSUE TITLE
Add support for Ruby 1.9

### ISSUE THREAD

**Issue by baurmatt** [unixcharles/acme-client#44]
Ubuntu 14.04 doesn't include support for Ruby 2.1. I know I could installed it through a PPA or rvm, but it would prefer not to. Is it possible to add support for Ruby 1.9?

Thanks!

**Comment by jhass** [comment]
Ruby 1.9 is out of official security maintenance and 2.0 will be by next March. Rails 5 will demand Ruby 2.2 or newer. 

I strongly vote against the maintenance burden of supporting a Ruby version that the community no longer uses and that is only "supported" through policies of distribution vendors.

**Comment by unixcharles** [comment]
There is an extensive use of keyword arguments in the gem. I'm not sure it would make sense given the complexity it would add for supporting deprecated versions of MRI.

Do you have a specific use case were rbenv/rvm/chruby is not appropriate? Generally speaking, most ruby application are deployed/developed on those.

**Comment by baurmatt** [comment]
The use case is a Puppet environment with thousands of servers which are running Ubuntu 14.04 LTS and I would like to develop a Puppet module for letsencrypt to automate the certificate requesting process.

I totally aware of the fact that 1.9 is out of support by the Ruby developer them self and I agree fully with @jhass that you _should_ use 2.1 or newer. But since those servers are running a LTS for a reason, I can't just upgrade Ruby on all of them, especially since some of them run applications which are developed for Ruby 1.9.

Anyway, today I developed some code which allows me to do what I wanted, so this issue can in fact be closed. Please let me know if you change your mind about this.

Thanks!
