### ISSUE TITLE
Keep token for two steps validation

### ISSUE THREAD

**Issue by Soullivaneuh** [unixcharles/acme-client#50]
This issue is the following of #48 but with another issue.

I generate validation file and token on `acme_01.rb`, without validation:

```ruby
# We're going to need a private key.
require 'openssl'
private_key = OpenSSL::PKey::RSA.new(2048)

File.write('private_key', private_key)

print private_key

endpoint = 'https://acme-v01.api.letsencrypt.org/'

require 'acme/client'
client = Acme::Client.new(private_key: private_key, endpoint: endpoint)

registration = client.register(contact: 'mailto:soullivaneuh@gmail.com')
registration.agree_terms

authorization = client.authorize(domain: 'sullivansenechal.com')

challenge = authorization.http01

puts 'Filename: ' + challenge.filename # => ".well-known/acme-challenge/:some_token"
puts 'File content:' + challenge.file_content # => 'string token and JWK thumbprint'
puts 'Content type: ' + challenge.content_type
puts 'Token: ' + challenge.token

File.write('private_token', challenge.token)

FileUtils.mkdir_p( File.join( 'public', File.dirname( challenge.filename ) ) )
File.write( File.join( 'public', challenge.filename), challenge.file_content )
```

The problem is, when I want to launch `acme_02.rb` to validate the file, this one has changed.

I noticed that the challenge need a token, so I'm trying to store it and use it on the second script:

```ruby
# We're going to need a private key.
require 'openssl'
private_key = OpenSSL::PKey::RSA.new(File.read('private_key'))

print private_key

endpoint = 'https://acme-v01.api.letsencrypt.org/'

require 'acme/client'
client = Acme::Client.new(private_key: private_key, endpoint: endpoint)

authorization = client.authorize(domain: 'sullivansenechal.com')

challenge = authorization.http01(token: File.read('private_token'))

puts 'Filename: ' + challenge.filename # => ".well-known/acme-challenge/:some_token"
puts 'File content:' + challenge.file_content # => 'string token and JWK thumbprint'
puts 'Content type: ' + challenge.content_type
puts 'Token: ' + challenge.token

challenge.request_verification # => true
puts challenge.verify_status # => 'pending'
sleep(1)
puts challenge.verify_status # => 'valid'

# We're going to need a certificate signing request. If not explicitly
# specified, the first name listed becomes the common name.
csr = Acme::Client::CertificateRequest.new(names: %w[sullivansenechal.com www.sullivansenechal.com])

# We can now request a certificate, you can pass anything that returns
# a valid DER encoded CSR when calling to_der on it, for example a
# OpenSSL::X509::Request too.
certificate = client.new_certificate(csr) # => #<Acme::Client::Certificate ....>

# Save the certificate and key
File.write("privkey.pem", certificate.request.private_key.to_pem)
File.write("cert.pem", certificate.to_pem)
File.write("chain.pem", certificate.chain_to_pem)
File.write("fullchain.pem", certificate.fullchain_to_pem)
```

But I got the following error:

```bash
acme_02.rb:14:in `<main>': wrong number of arguments (1 for 0) (ArgumentError)
```

So I assume `challenge = authorization.http01(token: File.read('private_token'))` is not the way to do.

How can I pass the token to the authorization challenge?

**Comment by jhass** [comment]
You probably can do something like

```rb
# Persist challenge
File.write("challenge", {"token" => challenge.token, "uri" => challenge.uri})

# Restore challenge
challenge = Acme::Client::Resources::Challenges::HTTP01.new(client, JSON.parse(File.read("challenge")))
challenge.request_verification
```

but I wouldn't consider that public and future proof API, at least at the moment. I'd say prepare for unannounced breaking changes in that area.

The intentional workflow of ACME and thus this gem is to fully automate the process, thus your approach of splitting the flow it into two programs is the reason you're facing so many headaches. A compromise (and that's what the official client does in manual mode) is to wait for the user to confirm continuation of the process, so the initial objects stay alive and can be used subsequently.

**Comment by Soullivaneuh** [comment]
> A compromise (and that's what the official client does in manual mode) is to wait for the user to confirm continuation of the process, so the initial objects stay alive and can be used subsequently.

Indeed, but I have to implement this system with a web interface. In a nutshell, like this:

1. User use the certificate creation form with wanted domain
2. We contact letsencrypt ACME api to get a challenge token and file
3. We tell the user to add this file to his own webserver
4. The user launch the validation, the second script the launcher

With this process, I can't have a waiting program.

Thanks for your proposition, I'll try it.

**Comment by Soullivaneuh** [comment]
@jhass Thanks, your solution works well. You just have to add a `.to_json` at the end of the hash:

```ruby
File.write("challenge", {"token" => challenge.token, "uri" => challenge.uri}.to_json)
```

**Comment by itspriddle** [comment]
I'm attempting to do something very similar and would love to see a formal API for this. 

In my case we are provisioning a website and DNS for the user and uploading the challenge for them. But since DNS propagation can take some time I need a way to run the verify and cert generation steps at a later time, possibly multiple times if the verification fails at first.

If you have any thoughts on what the API would be for this I'd be happy to work on a patch. If not, or if you need more time to think about it, the proposed solution does seem to work in my limited testing and I will just keep an eye out for breaking changes on new gem releases.

**Comment by unixcharles** [comment]
> In my case we are provisioning a website and DNS for the user and uploading the challenge for them. But since DNS propagation can take some time I need a way to run the verify and cert generation steps at a later time, possibly multiple times if the verification fails at first.

Thats a totally legit use case.

I think that we should have a serialization method on the `Acme::Client::Resources::Challenges::Base` and an utility method to load them back from the client object.

So that we can do something like:

```ruby
client.challenge_from_hash(challenge.to_h)
```

And possibly the same for the entire authorization object.

```ruby
client.authorization_from_hash(authorization.to_h)
```
