### ISSUE TITLE
Is it possible to follow 301 redirects from www to non-www (and vice versa) for verification?

### ISSUE THREAD

**Issue by worldlywisdom** [unixcharles/acme-client#56]
Thanks for developing this client - very useful!

I'm having a hard time updating my LE certificates due to verification issues. I'm currently using the `rack-host-redirect` gem to strip `www` from all requests:

    use Rack::HostRedirect, {
        'www.example.com' => 'example.com'
    }

When LE verification (via the http-01 method) attempts to verify the response at `www.example.com/.well-known/acme-challenge/*` (where `*` is the challenge string), verification fails because of the 301 redirect, even though the server provides the correct response after the redirect. (Verification passes on the non-www root domain.)

Does the spec allow for following these sorts of 301 redirects during verification before parsing the response, like it allows for 301 redirects from `http://` to `https://`? It would make adding and updating LE certificates much easier, since `www` redirection is extremely common.

Not sure if this is an `acme-client` thing or a Let's Encrypt spec issue - apologies if I'm bringing this up in the wrong place.

**Comment by unixcharles** [comment]
I think that would go against the spec. Also, this request is performed by the acme server, so this is not controlled by the client (see https://github.com/letsencrypt/boulder).

One option would be to subclass `Rack::HostRedirect` to ignore `.well-known/acme-challenge/*` or serve the token directly from rack and mount the middle before `Rack::HostRedirect`.

**Comment by worldlywisdom** [comment]
Got it - thought I'd ask to be sure. I'm already in contact with the maintainer of `rack-host-redirect` to add a skip/ignore feature. Serving the token directly from Rack is also a good idea. Thanks for your help!
