### ISSUE TITLE
Load error when in gemfile

### ISSUE THREAD

**Issue by ryanstout** [unixcharles/acme-client#6]
I get the following when I put the acme-client in my Gemfile and run ```bundle console```

```....acme-client-d08c04140f3a/lib/acme/client.rb:1:in `<top (required)>': uninitialized constant Acme (NameError)```

**Comment by ryanstout** [comment]
Ok, this one looks like its because bundler tries to do ```require 'acme-client'```  But the path in lib is acme_client.

**Comment by unixcharles** [comment]
Sorry about that! Will look into it.

**Comment by ryanstout** [comment]
thanks!

**Comment by unixcharles** [comment]
Should be fixed in `0.1.2`.

I'm not to sure why bundler didn't complain locally when doing `gem 'acme-client', path: '../acme-client'`.
