### ISSUE TITLE
challenge.verify_status keeps returning 'invalid'

### ISSUE THREAD

**Issue by jbwyatt4** [unixcharles/acme-client#60]
From the example code on the front page I keep getting 'invalid'.

Is there a way to query why?

**Comment by jhass** [comment]
I doubt you used the exact code, at least you have replaced the domains you want a certificate for. Could you share the _exact_ code you used (with the real domain).

**Comment by jbwyatt4** [comment]
Of course not.

  require 'openssl'
  private_key = OpenSSL::PKey::RSA.new(4096)

  endpoint = "https://acme-v01.api.letsencrypt.org/"
  #endpoint = "#{node['letsencrypt']['ENDPOINT']}"

  client = Acme::Client.new(private_key: private_key, endpoint: endpoint)

  registration = client.register(contact: "mailto:johnwyatt@wyatttechcourses.com")
  #registration = client.register(contact: node['letsencrypt']['contact_email'])

  registration.agree_terms

  authorization = client.authorize(domain: "wyatttechcourses.com")
  #authorization = client.authorize(domain: node['letsencrypt']['domain'])

  challenge = authorization.http01

  # Create folder
  directory '/root/deploy' do
    owner 'root'
    group 'root'
    mode '0700'
    action :create
  end

  # Save challenge for later
  file '/root/deploy/challenge.json' do
    content challenge.to_h.to_json
    mode '0700'
    owner 'root'
    group 'root'
  end

  Chef::Log.warn("Request Status: #{challenge.request_verification}")
  Chef::Log.warn("Pending Status: #{challenge.verify_status}")
  sleep(10)
  sta = challenge.verify_status # leave after sleep, is needed to query
  Chef::Log.warn("Verified Status: #{sta}")

**Comment by jhass** [comment]
Before requesting validation of the http-01 challenge, you need to provision a file at `http://wyatttechcourses.com/#{challenge.filename}` containing `challenge.file_content`.

Where do you deploy the challenge in your code?

**Comment by jbwyatt4** [comment]
I see; I misread that as optional. I have made /var/challenge as the directory

  require 'openssl'
  private_key = OpenSSL::PKey::RSA.new(4096)

  endpoint = "https://acme-v01.api.letsencrypt.org/"
  #endpoint = "#{node['letsencrypt']['ENDPOINT']}"

  client = Acme::Client.new(private_key: private_key, endpoint: endpoint)

  registration = client.register(contact: "mailto:johnwyatt@wyatttechcourses.com")
  #registration = client.register(contact: node['letsencrypt']['contact_email'])

  registration.agree_terms

  authorization = client.authorize(domain: "wyatttechcourses.com")
  #authorization = client.authorize(domain: node['letsencrypt']['domain'])

  challenge = authorization.http01

  # Create folder
  directory '/var/challenge' do
    owner 'root'
    group 'root'
    mode '0755'
    action :create
  end

  # Save challenge for later
  file "/var/challenge/#{challenge.filename}" do
    content challenge.to_h.to_json
    mode '0755'
    owner 'root'
    group 'root'
  end

  Chef::Log.warn("Request Status: #{challenge.request_verification}")
  Chef::Log.warn("Pending Status: #{challenge.verify_status}")
  sleep(10)
  sta = challenge.verify_status # leave after sleep, is needed to query
  Chef::Log.warn("Verified Status: #{sta}")

**Comment by jhass** [comment]
And you configured your webserver to serve that? I'm not too familiar with Chef, that file is created on the server before further code is executed?

**Comment by jbwyatt4** [comment]
No I did not. I thought the gem ran it's own server. Let me try to get nginx to serve the file on port 80.

**Comment by unixcharles** [comment]
> I thought the gem ran it's own server.

No, I think that would be out of scope for the client. Its mean to be used for tight integration within an system infrastructure.

Is it the readme that created that confusion? We added an example on how to do this using a simple ruby server but this might be just creating more confusion.

**Comment by jbwyatt4** [comment]
I think I just assumed it had it's own server.

Would you post a link to the example code?

**Comment by unixcharles** [comment]
its in the readme

**Comment by jbwyatt4** [comment]
Which readme? It's not the one on the main page.

**Comment by jbwyatt4** [comment]
So I tried running without Chef and I get the same result. Only an invalid status and I don't know why.

I copied example commands to run at /root temporarily

require 'openssl'
private_key = OpenSSL::PKey::RSA.new(4096)
endpoint = 'https://acme-v01.api.letsencrypt.org/'
require 'acme/client'
client = Acme::Client.new(private_key: private_key, endpoint: endpoint)
registration = client.register(contact: 'mailto:johnwyatt@wyatttechcourses.com')
registration.agree_terms
authorization = client.authorize(domain: 'wyatttechcourses.com')
challenge = authorization.http01
FileUtils.mkdir_p( File.join( 'public', File.dirname( challenge.filename ) ) )
File.write( File.join( 'public', challenge.filename), challenge.file_content )

ruby -run -e httpd public -p 8080 --bind-address 0.0.0.0 # in another terminal window, confirmed it sends a file

challenge = client.challenge_from_hash(JSON.parse(File.read('challenge')))
challenge.request_verification # true
challenge.verify_status # pending, then invalid

filename returns as ".well-known/acme-challenge/7i1AGT-QdN3_Qs_8QV3xUkwpHR_CS8UWDL7xvvcQ3cI"
actual file offers a download with 7i1AGT-QdN3_Qs_8QV3xUkwpHR_CS8UWDL7xvvcQ3cI.QU7CBnstk8kl_hBh8MSMR6WM-uniUG8wucf7WaO_GMQ

**Comment by jhass** [comment]
http-01 verifies over port 80, not 8080.

**Comment by jbwyatt4** [comment]
Yes, I tried that. Still returning as invalid.

**Comment by jbwyatt4** [comment]
Thankyou for your help, but I was unable to get the gem working. I did get the reference let's encrypt code to work with Chef. Closing the issue.
