### ISSUE TITLE
`record_name` in DNS01 is invalid for subdomains

### ISSUE THREAD

**Issue by Temikus** [unixcharles/acme-client#69]
DNS01 authorisation will never succeed if the `record_name` parameter is used, since subdomain needs to be specified like:
`_acme-challenge.www` for `www.example.com`
, however, the client suggests:
`_acme-challenge`

**Comment by jhass** [comment]
Well, it's debatable what should be returned here. Currently the user is asked to built the FQDN themselves, `record_name` is merely there to  conveniently return the currently standardized prefix label, in case it will ever change, thus perhaps it should be called `record_prefix` or `record_label`. This is similar and consistent to what for example `filename` for `Acme::Client::Resources::Challenges::HTTP01` returns, where we'll never be able to return the full filesystem path, or `content_type` which is too just a static value.

**Comment by weppos** [comment]
`record_name` is the name of the DNS challenge record as per [ACME specs](https://tools.ietf.org/html/draft-ietf-acme-acme-10#section-8.4). It's essentially the name you must prepend to the identifier (domain name).

It doesn't make any assumption about the identifier. In fact, your assumption about `www.example.com` is potentially incorrect as you assume that `example.com` is the domain.

But if we talk in term of zones, the assumption is incorrect. Let's assume you control the zone `foo.bar.xyz` (that ironically it's actually a potentially valid subdomain). You want to request a certificate for:

```
www.foo.bar.xyz
```

The library would have to guess whether the `record_name` is:

- _acme-challenge.www
- _acme-challenge.www.foo
- _acme-challenge.www.foo.bar

But it all depends on what zone you control and what you consider being the base name. You could be the owner of the entire `bar.xyz` zone, in that case for you the name that would make sense is `_acme-challenge.www.foo`. But if you are an user of the `bar.xyz` zone with control only over the `foo.bar.xyz` zone, then you would think that `_acme-challenge.www` is the correct name.

Moving away from hypothetical names and applying to real world use cases, it would be the same confusion for:

```
example.uk
example.co.uk
foo.uk
```

and so on. Long story short, the only 2 possible meaningful values for record_name are either:

- the qualified name: `_acme-challenge.` + the identifier part
- the challenge name: `_acme-challenge`

**Comment by Temikus** [comment]
@weppos That was very insightful, thanks for the writeup!

**Comment by unixcharles** [comment]
I just assumed that the end user, being the one doing the challenge, would know what it mean for them in that context. I can see how that can be confusing in most normal scenario.

I would be open to have a `fully_qualified_record_name` method or something with meaningful semantic if that can clarify the situation.
