### ISSUE TITLE
Q: Re-using challenge from hash multiple times

### ISSUE THREAD

**Issue by jnummelin** [unixcharles/acme-client#78]
I'm trying to re-use the challenge from a stored hash. I can re-use it once properly, but any subsequent usage seems to fail with error `Unable to update challenge :: Response does not complete challenge`.

Is there some one-time nonce or something encoded into the token or am I doing something really wrong? I'm following the steps from the README tutorial, only change is that I'm storing the challenge hash into MongoDB but that should not really matter as I'm able to re-use the challenge once.

We're using the DNS verification so we need to be able to do this in two steps. Would like to be able to re-use the challenge multiple times since the verification might fail and has to be retried. Now the only alternative seems to be to create the authorization from scratch thus changing the DNS record content also. :(

**Comment by jnummelin** [comment]
I can reproduce this with following:
```
private_key = ... # load private key from storage
endpoint = 'https://acme-staging.api.letsencrypt.org/'
client = Acme::Client.new(private_key: private_key, endpoint: endpoint, connection_options: { request: { open_timeout: 5, timeout: 5 } })
dns_challenge = client.authorize(domain: 'example.org').dns01
dns_challenge_hash = dns_challenge.to_h
c = client.challenge_from_hash(dns_challenge_hash)
c.request_verfification # => true
c = client.challenge_from_hash(dns_challenge_hash)
c.request_verfification # => Failure
```
The last call throws: 
```
Acme::Client::Error::Malformed: Unable to update challenge :: Response does not complete challenge
```

Any idea what could be causing this?

**Comment by unixcharles** [comment]
That would be the server responsibility to decide if you can retry the challenge after a failure, I don't think its part of the spec. You might ask in [builder](http://github.com@letsenencrypt/builder/).

A simpler approach would be to query the nameserver to make sure the token is present before requesting it using resolv

http://ruby-doc.org/stdlib-1.9.3/libdoc/resolv/rdoc/Resolv/DNS.html

**Comment by jnummelin** [comment]
Thanks for the info. I tried to find this in the spec but couldn't find it thus wanted to check. I was already planning for the Resolv route anyway. :)
