### ISSUE TITLE
Ruby < 2.2.2

### ISSUE THREAD

**Issue by jopelope** [unixcharles/acme-client#80]
Hello, I am running an embedded version of Ruby that is still below 2.2.2. I saw the patch https://github.com/unixcharles/acme-client/commit/0e54673de0ab81d5989420671f386f355c059eaa, but even acme-client 0.3.6 complains that "activesupport requires Ruby version >= 2.2.2".

Now when seeing that patch I wonder if it shouldn't be greater-equal instead of less-equal?

Thanks!

**Comment by unixcharles** [comment]
> Hello, I am running an embedded version of Ruby that is still below 2.2.2. I saw the patch 0e54673, but even acme-client 0.3.6 complains that "activesupport requires Ruby version >= 2.2.2".

The Gemfile are not taken in consideration by rubygems. Its only there for development/test.

I seem that activesupport added a ruby version requirement to 5.0.0 but this is not taken into consideration when fetching the dependencies.

> Now when seeing that patch I wonder if it shouldn't be greater-equal instead of less-equal?

The client will work with any relatively recent version of the activesupport (its in actually a dependancy of jwt-ruby).

You can freeze activesupport in your Gemfile the way I did our test in https://github.com/unixcharles/acme-client/commit/0e54673de0ab81d5989420671f386f355c059eaa

We planned to work on removing our dependency on jwt-ruby so if you want to help on that let me know.
