### ISSUE TITLE
Acme::Client::Error::Malformed: Unable to update challenge :: Response does not complete challenge

### ISSUE THREAD

**Issue by nickmcdonnough** [unixcharles/acme-client#82]
Hi. I believe this may be a problem with the keyAuthorization property. Here is a description of what I'm doing.

I am working on a cert ordering system that handles things asynchronously. The process is started with:

```ruby
authorization = client.authorize(domain: 'some.domain.com')
challenge = authorization.http01
order.challenge = challenge.to_h # stored as jsonb in postgres
```

I also save the DV file info (path and file contents). The next step is that I have another system upload the DV file to the site. This all works fine. The problem is at the third step. I verify that the DV file was uploaded correctly (it was) and then I retrieve the challenge info from the database.

```ruby
challenge = client.challenge_from_hash(order.challenge)
challenge.request_verficiation
```

It is at this point that the error is raised. Is there something other than the data retrieved in `challenge.to_h` that I should be saving? The boulder source leads me to believe the problem is with the keyAuthorization which I'm not sure makes sense.

Any thoughts would be greatly appreciated.

**Comment by jhass** [comment]
It would be great if you could provide a live example of a failing challenge and the steps you took to verify it's set up correctly.

**Comment by nickmcdonnough** [comment]
I'm having a hard time replicating the problem outside of the environment in which the code currently exists. Because it is for work I cannot easily share it here. I'm going to close this issue and continue debugging. I'll report back if I learn anything useful. Thanks.

**Comment by nickmcdonnough** [comment]
I have completed debugging and the problem was indeed on my end. Everything is fine with the client. Thanks.
