### ISSUE TITLE
Older versions of OpenSSL don't set a CSR version, which LE now requires

### ISSUE THREAD

**Issue by will-in-wi** [unixcharles/acme-client#84]
Reported in https://github.com/will-in-wi/letsencrypt-webfaction/issues/38

Turns out this was added in https://github.com/letsencrypt/boulder/issues/1902

This was fixed in CertBot by explicitly adding a version number https://github.com/certbot/certbot/pull/2529

I think this'll be fixed by adding `csr.version = 2` in `Acme::Client::CertificateRequest#generate`. I'm getting a PR ready once I can test that it really fixes the problem.

**Comment by unixcharles** [comment]
PR are most welcome :)
