### ISSUE TITLE
Doesn't locate Faraday correctly

### ISSUE THREAD

**Issue by technion** [unixcharles/acme-client#9]
Hi,

I am running into the following errors relating to Faraday when using this client from the CLI.

$ bundle exec ./bin/console
2.2.0 :001 > private_key = OpenSSL::PKey::RSA.new(2048)
 => #<OpenSSL::PKey::RSA:0x005648bd221148>
2.2.0 :002 > endpoint = 'https://acme-v01.api.letsencrypt.org/directory'
 => "https://acme-v01.api.letsencrypt.org/directory"
2.2.0 :003 > client = Acme::Client.new(private_key: private_key, endpoint: endpoint)
...
2.2.0 :004 > registration = client.register(contact: 'mailto:test@lolware.net')
NameError: uninitialized constant Acme::Client::Faraday
        from acme-client/lib/acme/client.rb:51:in `connection'
        from acme-client/lib/acme/client.rb:23:in `register'
        from (irb):4

Note this is after I applied #8.

**Comment by technion** [comment]
Nothing like spending hours on a problem, only to open an issue and immediately identify it. See the PR.

**Comment by unixcharles** [comment]
Thanks @technion
