### ISSUE TITLE
Could you please consider adding tags as same as releases on rubygems.org ?

### ISSUE THREAD

**Issue by sawanoboly** [unixcharles/acme-client#92]
Hi, thank you for kindly maintenance. If possible, would you please add versions tag to the this repository ?

**Comment by unixcharles** [comment]
What is the use case exactly?

**Comment by jhass** [comment]
I actually often use tags to get a definitive picture of what changed between any two versions of a project.

**Comment by unixcharles** [comment]
Fair enough. I'll add tags in the future releases.

**Comment by sawanoboly** [comment]
Thanks 😃
