### ISSUE TITLE
Where to set: {:ca_path => '/etc/ssl/certs'} ?

### ISSUE THREAD

**Issue by paradisaeidae** [unixcharles/acme-client#93]
When setting api server to https://acme-staging.api.letsencrypt.org/, IdenTrustCA.pem is required to be in OPENSSL cert directory.
How to pass (/etc/ssl/certs) through to openssl's ca_path?
Can be done at cli with export SSL_CERT_FILE=....
export SSL_CERT_DIR=/etc/ssl/certs works.
Though prefer to set in ruby.

**Comment by paradisaeidae** [comment]
When setting api server to https://acme-staging.api.letsencrypt.org/, IdenTrustCA.pem is required to be in OPENSSL cert directory.
How to pass this through to openssl's ca_path?
Can be done at cli with export SSL_CERT_FILE=....
Though prefer to set in ruby.

**Comment by jhass** [comment]
Well, a recent OpenSSL/Ruby should set the default location automatically.

However you can:

* Pass `connection_options` as the last parameter to `Acme::Client.new`. This is passed on to `Faraday.new`.
* Change the settings of `client.connection`.
* I guess changing the settings of `Faraday.default_connection` or `Faraday.default_adapter` might work too.

**Comment by paradisaeidae** [comment]
I am using ruby 2.2.2.
Many default ruby installs set verify to nil.
So it appears the ssl connection is fine.
Though the destination cert is not being checked by a local CA cert.
I've tried to set ca_path before and after client = Acme::Client.new(...
...with...
Faraday.default_connection.ssl.ca_path = '/etc/ssl/certs/'
indeed visible with pry,
@ssl=#<Faraday::SSLOptions ca_path="/etc/ssl/certs/">
Could it be that there is a fresh ssl context being generated somewhere in there?
I admit, I am using a locally compiled OpenSSL.
So the SSL defaults may not be as a default ruby install expects them.
I am reviewing the settings on my openSSL configure.

**Comment by jhass** [comment]
>  Many default ruby installs set verify to nil.

I see it way too often in application code, but not as a installation wide default, got any source on that?

Try `Acme::Client.new(..., ssl: {ca_path: "/etc/ssl/certs"})`.

**Comment by paradisaeidae** [comment]
Fair comment. Retract assertion.Plead too many tabs open.

**Comment by unixcharles** [comment]
Setting verify to nil is very dangerous, it defeat the purpose of SSL.

See http://mislav.net/2013/07/ruby-openssl/

**Comment by paradisaeidae** [comment]
verify == nil is dangerous.
This is known and understood.
Preferring to download and compile OpenSSL here.
So certs dir will be different as install dir is not default.
Adjusting certs dir is proving difficult.
Possibly for good reason/s.
Avoiding further issue here by cp -a  /etc/ssl/certs/*  OpenSSLInstallDir/certs/
