### ISSUE TITLE
Set X509 version when generating self-signed certificates

### ISSUE THREAD

**Issue by rolandshoemaker** [unixcharles/acme-client#97]
Follow up to #84, this also needs to be done when using OpenSSL to generate self-signed certificates for `tls-sni` type challenges.

**Comment by phillipp** [comment]
Would it be possible to release with this so the client will continue working after Let's Encrypt deploys the new version (anytime soon)?

**Comment by unixcharles** [comment]
Just released 0.4.1

**Comment by phillipp** [comment]
Thank you!
